repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v4.5.0'
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/doublify/pre-commit-rust
  rev: 'v1.0'
  hooks:
  - id: fmt
    name: rustfmt
    entry: rustfmt
    language: system
    types: [rust]
- repo: local
  hooks:
  - id: clippy
    name: clippy
    entry: cargo clippy -- -D warnings
    language: system
    types: [rust]
    pass_filenames: false
- repo: local
  hooks:
  - id: cargo-check
    name: cargo check
    entry: cargo check
    language: system
    types: [rust]
    pass_filenames: false

